### ISSUE TITLE
How to solve this problem:No context argument was provided to nengo_ocl.Simulator

### ISSUE THREAD

**Issue by ParrtZhang** [nengo/nengo-ocl#153]
The detail of the problem is:

```
No context argument was provided to nengo_ocl.Simulator
Calling pyopencl.create_some_context() for you now:
Traceback (most recent call last):

  File "<ipython-input-2-0cc904b7b505>", line 1, in <module>
    runfile('/home/zhangpeng/桌面/4th Tasks - Papers for Sequence Learning in SNNs/FOLLOW-master/input_ff_rec_transform_nengo_ocl.py', wdir='/home/zhangpeng/桌面/4th Tasks - Papers for Sequence Learning in SNNs/FOLLOW-master')

  File "/home/zhangpeng/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/zhangpeng/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/zhangpeng/桌面/4th Tasks - Papers for Sequence Learning in SNNs/FOLLOW-master/input_ff_rec_transform_nengo_ocl.py", line 1147, in <module>
    if OCL: sim = nengo_ocl.Simulator(mainModel,dt=0.001)

  File "/home/zhangpeng/anaconda3/lib/python3.6/site-packages/nengo_ocl/simulator.py", line 207, in __init__
    Simulator.some_context = cl.create_some_context()

  File "/home/zhangpeng/anaconda3/lib/python3.6/site-packages/pyopencl/__init__.py", line 591, in create_some_context
    platforms = get_platforms()

  File "/home/zhangpeng/anaconda3/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 691, in get_platforms
    _handle_error(_lib.get_platforms(platforms.ptr, platforms.size))

  File "/home/zhangpeng/anaconda3/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e

LogicError: clGetPlatformIDs failed: <unknown error -1001>
```

Thanks for your review!

**Comment by hunse** [comment]
That's an OpenCL or PyOpenCL error. You'll have to look at their
documentation to learn how to install them properly.

**Comment by ParrtZhang** [comment]
Thank you! professor
