### ISSUE TITLE
nengo_ocl installation 

### ISSUE THREAD

**Issue by assadRasheed** [nengo/nengo-ocl#156]
i am trying to install nengo ocl but the following errors are confronting .dont know how to rectify these errors .

```
  writing dependency_links to pyopencl.egg-info\dependency_links.txt
  writing top-level names to pyopencl.egg-info\top_level.txt
  reading manifest file 'pyopencl.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'src\c_wrapper\*.hpp'
  warning: no files found matching 'doc\_static\*.css'
  warning: no files found matching 'doc\_templates\*.html'
  writing manifest file 'pyopencl.egg-info\SOURCES.txt'
  creating build\lib.win-amd64-3.5\pyopencl\cl
  copying pyopencl\cl\pyopencl-airy.cl -> build\lib.win-amd64-3.5\pyopencl\cl
  copying pyopencl\cl\pyopencl-bessel-j-complex.cl -> build\lib.win-amd64-3.5\py
opencl\cl
  copying pyopencl\cl\pyopencl-bessel-j.cl -> build\lib.win-amd64-3.5\pyopencl\c
l
  copying pyopencl\cl\pyopencl-bessel-y.cl -> build\lib.win-amd64-3.5\pyopencl\c
l
  copying pyopencl\cl\pyopencl-complex.h -> build\lib.win-amd64-3.5\pyopencl\cl
  copying pyopencl\cl\pyopencl-eval-tbl.cl -> build\lib.win-amd64-3.5\pyopencl\c
l
  copying pyopencl\cl\pyopencl-hankel-complex.cl -> build\lib.win-amd64-3.5\pyop
encl\cl
  copying pyopencl\cl\pyopencl-ranluxcl.cl -> build\lib.win-amd64-3.5\pyopencl\c
l
  creating build\lib.win-amd64-3.5\pyopencl\cl\pyopencl-random123
  copying pyopencl\cl\pyopencl-random123\array.h -> build\lib.win-amd64-3.5\pyop
encl\cl\pyopencl-random123
  copying pyopencl\cl\pyopencl-random123\openclfeatures.h -> build\lib.win-amd64
-3.5\pyopencl\cl\pyopencl-random123
  copying pyopencl\cl\pyopencl-random123\philox.cl -> build\lib.win-amd64-3.5\py
opencl\cl\pyopencl-random123
  copying pyopencl\cl\pyopencl-random123\threefry.cl -> build\lib.win-amd64-3.5\
pyopencl\cl\pyopencl-random123
  running build_ext
  generating cffi module 'build\\temp.win-amd64-3.5\\Release\\pyopencl._cffi.cpp
'
  creating build\temp.win-amd64-3.5
  creating build\temp.win-amd64-3.5\Release
  ---------------------------------------------------------------------------
  Sorry, your build failed. Try rerunning configure.py with different options.
  ---------------------------------------------------------------------------
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\saim\AppData\Local\Temp\pip-build-0cf3ib26\pyopencl\setup.py"
, line 265, in <module>
      main()
    File "C:\Users\saim\AppData\Local\Temp\pip-build-0cf3ib26\pyopencl\setup.py"
, line 261, in main
      zip_safe=False)
    File "C:\Users\saim\AppData\Local\Temp\pip-build-0cf3ib26\pyopencl\aksetup_h
elper.py", line 21, in setup
      setup(*args, **kwargs)
    File "C:\Users\saim\Anaconda34\lib\site-packages\setuptools\__init__.py", li
ne 129, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\saim\Anaconda34\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\saim\Anaconda34\lib\distutils\dist.py", line 955, in run_comm
ands
      self.run_command(cmd)
    File "C:\Users\saim\Anaconda34\lib\distutils\dist.py", line 974, in run_comm
and
      cmd_obj.run()
    File "C:\Users\saim\Anaconda34\lib\site-packages\wheel\bdist_wheel.py", line
 202, in run
      self.run_command('build')
    File "C:\Users\saim\Anaconda34\lib\distutils\cmd.py", line 313, in run_comma
nd
      self.distribution.run_command(command)
    File "C:\Users\saim\Anaconda34\lib\distutils\dist.py", line 974, in run_comm
and
      cmd_obj.run()
    File "C:\Users\saim\Anaconda34\lib\distutils\command\build.py", line 135, in
 run
      self.run_command(cmd_name)
    File "C:\Users\saim\Anaconda34\lib\distutils\cmd.py", line 313, in run_comma
nd
      self.distribution.run_command(command)
    File "C:\Users\saim\Anaconda34\lib\distutils\dist.py", line 974, in run_comm
and
      cmd_obj.run()
    File "C:\Users\saim\Anaconda34\lib\site-packages\cffi\setuptools_ext.py", li
ne 141, in run
      base_class.run(self)
    File "C:\Users\saim\Anaconda34\lib\site-packages\setuptools\command\build_ex
t.py", line 78, in run
      _build_ext.run(self)
    File "C:\Users\saim\Anaconda34\lib\site-packages\Cython\Distutils\old_build_
ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "C:\Users\saim\Anaconda34\lib\distutils\command\build_ext.py", line 307
, in run
      force=self.force)
    File "C:\Users\saim\Anaconda34\lib\distutils\ccompiler.py", line 1031, in ne
w_compiler
      return klass(None, dry_run, force)
    File "C:\Users\saim\Anaconda34\lib\distutils\cygwinccompiler.py", line 282,
in __init__
      CygwinCCompiler.__init__ (self, verbose, dry_run, force)
    File "C:\Users\saim\Anaconda34\lib\distutils\cygwinccompiler.py", line 157,
in __init__
      self.dll_libraries = get_msvcr()
    File "C:\Users\saim\Anaconda34\lib\distutils\cygwinccompiler.py", line 86, i
n get_msvcr
      raise ValueError("Unknown MS Compiler version %s " % msc_ver)
  ValueError: Unknown MS Compiler version 1900

  ----------------------------------------
  Failed building wheel for pyopencl
  Running setup.py clean for pyopencl
  Running setup.py bdist_wheel for pytools ... done
  Stored in directory: C:\Users\saim\AppData\Local\pip\Cache\wheels\d9\8d\51\f51
a45e5913656329179819cfe54aaf6234864ca69e90ff19f
Successfully built pytools
Failed to build pyopencl
Installing collected packages: appdirs, pytools, pyopencl, nengo-ocl
  Running setup.py install for pyopencl ... error
    Complete output from command C:\Users\saim\Anaconda34\python.exe -u -c "impo
rt setuptools, tokenize;__file__='C:\\Users\\saim\\AppData\\Local\\Temp\\pip-bui
ld-0cf3ib26\\pyopencl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);cod
e=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))
" install --record C:\Users\saim\AppData\Local\Temp\pip-p7_ruvnr-record\install-
record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\algorithm.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\array.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\bitonic_sort.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\bitonic_sort_templates.py -> build\lib.win-amd64-3.5\pyopen
cl
    copying pyopencl\cache.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\capture_call.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\cffi_cl.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\clmath.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\clrandom.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\cltypes.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\elementwise.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\invoker.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\ipython_ext.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\mempool.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\reduction.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\scan.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\tools.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\version.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\_buffers.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\_cluda.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\_mymako.py -> build\lib.win-amd64-3.5\pyopencl
    copying pyopencl\__init__.py -> build\lib.win-amd64-3.5\pyopencl
    creating build\lib.win-amd64-3.5\pyopencl\characterize
    copying pyopencl\characterize\performance.py -> build\lib.win-amd64-3.5\pyop
encl\characterize
    copying pyopencl\characterize\__init__.py -> build\lib.win-amd64-3.5\pyopenc
l\characterize
    creating build\lib.win-amd64-3.5\pyopencl\compyte
    copying pyopencl\compyte\array.py -> build\lib.win-amd64-3.5\pyopencl\compyt
e
    copying pyopencl\compyte\dtypes.py -> build\lib.win-amd64-3.5\pyopencl\compy
te
    copying pyopencl\compyte\__init__.py -> build\lib.win-amd64-3.5\pyopencl\com
pyte
    creating build\lib.win-amd64-3.5\pyopencl\compyte\ndarray
    copying pyopencl\compyte\ndarray\gen_elemwise.py -> build\lib.win-amd64-3.5\
pyopencl\compyte\ndarray
    copying pyopencl\compyte\ndarray\gen_reduction.py -> build\lib.win-amd64-3.5
\pyopencl\compyte\ndarray
    copying pyopencl\compyte\ndarray\setup_opencl.py -> build\lib.win-amd64-3.5\
pyopencl\compyte\ndarray
    copying pyopencl\compyte\ndarray\test_gpu_elemwise.py -> build\lib.win-amd64
-3.5\pyopencl\compyte\ndarray
    copying pyopencl\compyte\ndarray\test_gpu_ndarray.py -> build\lib.win-amd64-
3.5\pyopencl\compyte\ndarray
    copying pyopencl\compyte\ndarray\__init__.py -> build\lib.win-amd64-3.5\pyop
encl\compyte\ndarray
    running egg_info
    writing pyopencl.egg-info\PKG-INFO
    writing dependency_links to pyopencl.egg-info\dependency_links.txt
    writing top-level names to pyopencl.egg-info\top_level.txt
    writing requirements to pyopencl.egg-info\requires.txt
    reading manifest file 'pyopencl.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'src\c_wrapper\*.hpp'
    warning: no files found matching 'doc\_static\*.css'
    warning: no files found matching 'doc\_templates\*.html'
    writing manifest file 'pyopencl.egg-info\SOURCES.txt'
    creating build\lib.win-amd64-3.5\pyopencl\cl
    copying pyopencl\cl\pyopencl-airy.cl -> build\lib.win-amd64-3.5\pyopencl\cl
    copying pyopencl\cl\pyopencl-bessel-j-complex.cl -> build\lib.win-amd64-3.5\
pyopencl\cl
    copying pyopencl\cl\pyopencl-bessel-j.cl -> build\lib.win-amd64-3.5\pyopencl
\cl
    copying pyopencl\cl\pyopencl-bessel-y.cl -> build\lib.win-amd64-3.5\pyopencl
\cl
    copying pyopencl\cl\pyopencl-complex.h -> build\lib.win-amd64-3.5\pyopencl\c
l
    copying pyopencl\cl\pyopencl-eval-tbl.cl -> build\lib.win-amd64-3.5\pyopencl
\cl
    copying pyopencl\cl\pyopencl-hankel-complex.cl -> build\lib.win-amd64-3.5\py
opencl\cl
    copying pyopencl\cl\pyopencl-ranluxcl.cl -> build\lib.win-amd64-3.5\pyopencl
\cl
    creating build\lib.win-amd64-3.5\pyopencl\cl\pyopencl-random123
    copying pyopencl\cl\pyopencl-random123\array.h -> build\lib.win-amd64-3.5\py
opencl\cl\pyopencl-random123
    copying pyopencl\cl\pyopencl-random123\openclfeatures.h -> build\lib.win-amd
64-3.5\pyopencl\cl\pyopencl-random123
    copying pyopencl\cl\pyopencl-random123\philox.cl -> build\lib.win-amd64-3.5\
pyopencl\cl\pyopencl-random123
    copying pyopencl\cl\pyopencl-random123\threefry.cl -> build\lib.win-amd64-3.
5\pyopencl\cl\pyopencl-random123
    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.5\\Release\\pyopencl._cffi.c
pp'
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    ---------------------------------------------------------------------------
    Sorry, your build failed. Try rerunning configure.py with different options.

    ---------------------------------------------------------------------------
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\saim\AppData\Local\Temp\pip-build-0cf3ib26\pyopencl\setup.p
y", line 265, in <module>
        main()
      File "C:\Users\saim\AppData\Local\Temp\pip-build-0cf3ib26\pyopencl\setup.p
y", line 261, in main
        zip_safe=False)
      File "C:\Users\saim\AppData\Local\Temp\pip-build-0cf3ib26\pyopencl\aksetup
_helper.py", line 21, in setup
        setup(*args, **kwargs)
      File "C:\Users\saim\Anaconda34\lib\site-packages\setuptools\__init__.py",
line 129, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\saim\Anaconda34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\saim\Anaconda34\lib\distutils\dist.py", line 955, in run_co
mmands
        self.run_command(cmd)
      File "C:\Users\saim\Anaconda34\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "C:\Users\saim\Anaconda34\lib\site-packages\setuptools\command\instal
l.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\saim\Anaconda34\lib\distutils\command\install.py", line 539
, in run
        self.run_command('build')
      File "C:\Users\saim\Anaconda34\lib\distutils\cmd.py", line 313, in run_com
mand
        self.distribution.run_command(command)
      File "C:\Users\saim\Anaconda34\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "C:\Users\saim\Anaconda34\lib\distutils\command\build.py", line 135,
in run
        self.run_command(cmd_name)
      File "C:\Users\saim\Anaconda34\lib\distutils\cmd.py", line 313, in run_com
mand
        self.distribution.run_command(command)
      File "C:\Users\saim\Anaconda34\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "C:\Users\saim\Anaconda34\lib\site-packages\cffi\setuptools_ext.py",
line 141, in run
        base_class.run(self)
      File "C:\Users\saim\Anaconda34\lib\site-packages\setuptools\command\build_
ext.py", line 78, in run
        _build_ext.run(self)
      File "C:\Users\saim\Anaconda34\lib\site-packages\Cython\Distutils\old_buil
d_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "C:\Users\saim\Anaconda34\lib\distutils\command\build_ext.py", line 3
07, in run
        force=self.force)
      File "C:\Users\saim\Anaconda34\lib\distutils\ccompiler.py", line 1031, in
new_compiler
        return klass(None, dry_run, force)
      File "C:\Users\saim\Anaconda34\lib\distutils\cygwinccompiler.py", line 282
, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "C:\Users\saim\Anaconda34\lib\distutils\cygwinccompiler.py", line 157
, in __init__
        self.dll_libraries = get_msvcr()
      File "C:\Users\saim\Anaconda34\lib\distutils\cygwinccompiler.py", line 86,
 in get_msvcr
        raise ValueError("Unknown MS Compiler version %s " % msc_ver)
    ValueError: Unknown MS Compiler version 1900

    ----------------------------------------
Command "C:\Users\saim\Anaconda34\python.exe -u -c "import setuptools, tokenize;
__file__='C:\\Users\\saim\\AppData\\Local\\Temp\\pip-build-0cf3ib26\\pyopencl\\s
etup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n
', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Us
ers\saim\AppData\Local\Temp\pip-p7_ruvnr-record\install-record.txt --single-vers
ion-externally-managed --compile" failed with error code 1 in C:\Users\saim\AppD
ata\Local\Temp\pip-build-0cf3ib26\pyopencl\

(base) C:\Users\saim>
```

**Comment by xchoo** [comment]
Installing pyopencl on windows has always  been a pain. I think I've had the most success installing it using the precompiled `wheel` file from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopencl

I see that you are using Anaconda. So, download the desired `whl` file (in your case, it might be `pyopencl‑2018.1.1+cl21‑cp34‑cp34m‑win_amd64.whl` -- double check on what version of python you are using), then in your `conda` environment, do `pip install pyopencl‑2018.1.1+cl21‑cp34‑cp34m‑win_amd64.whl`.

If you do want to compile future python libraries from source, there are some instructions here: https://github.com/cython/cython/wiki/CythonExtensionsOnWindows, and you need a copy of MS.net or MS SDK (there should be a free one you can download). It needs to match the python version though.

**Comment by hunse** [comment]
If you're still having trouble, please ask this question to the PyOpenCL team. They will be much more familiar with the ins and outs of installing PyOpenCL than we are.
