### ISSUE TITLE
Make_step for bandpass filters ?

### ISSUE THREAD

**Issue by MenelikV** [nengo/nengo-ocl#84]
Hello,

Nengo_ocl is working fine with standard synapses but my project aims to use also band pass filters synapses.
Taking the Github version of Nengo_ocl (the one from pip does not handle that of filter for synapses), I got one error from the `plan_SimSynapse` function which (if I good understood the code of that function) lies on `make_step` function of Nengo. 
The later is not implemented in Nengo and I am wondering if there is a way to implement it knowing I have only bandpass filters.
(Maybe like the `LinearFilter` class from `synapse.py` ?)

Thanks in advance for your tips, 

Ménélik

**Comment by hunse** [comment]
Nengo OCL should now fully support the LinearFilter class, so if you can write your filter as a linear one in discrete or continuous time, you should be able to run it in both Nengo and Nengo OCL.

What error did you get?

**Comment by MenelikV** [comment]
With the Github version (`0.1.1.dev0`) I got following error :
```python
Traceback (most recent call last):
  File "model_2_offline_9_ocl.py", line 481, in <module>
    model = main(sys.argv[1], sys.argv[2])
  File "model_2_offline_9_ocl.py", line 475, in main
    change_every = change_every, nb_signals = nb_signals)
  File "model_2_offline_9_ocl.py", line 423, in run_and_plot
    sim = nengo_ocl.Simulator(model, dt, context = ctx)
  File "/home/menelou/MasterArbeit/Code/Nengo/nengo_voja/nengo_ocl-master/nengo_ocl/sim_ocl.py", line 64, in __init__
    self, network=network, dt=dt, seed=seed, model=model)
  File "/home/menelou/MasterArbeit/Code/Nengo/nengo_voja/nengo_ocl-master/nengo_ocl/sim_npy.py", line 442, in __init__
    self._plan.extend(self.plan_op_group(op_type, op_list))
  File "/home/menelou/MasterArbeit/Code/Nengo/nengo_voja/nengo_ocl-master/nengo_ocl/sim_npy.py", line 453, in plan_op_group
    return getattr(self, 'plan_' + op_type.__name__)(ops)
  File "/home/menelou/MasterArbeit/Code/Nengo/nengo_voja/nengo_ocl-master/nengo_ocl/sim_ocl.py", line 264, in plan_SimSynapse
    A = self.RaggedArray([f.den for f in steps])
AttributeError: 'functools.partial' object has no attribute 'den'
```
With the pip version : 
```python
Traceback (most recent call last):
  File "model_2_offline_9_ocl.py", line 481, in <module>
    model = main(sys.argv[1], sys.argv[2])
  File "model_2_offline_9_ocl.py", line 475, in main
    change_every = change_every, nb_signals = nb_signals)
  File "model_2_offline_9_ocl.py", line 423, in run_and_plot
    sim = nengo_ocl.Simulator(model, dt, context = ctx)
  File "/home/menelou/MasterArbeit/Code/Nengo/nengo_voja/local/lib/python2.7/site-packages/nengo_ocl/sim_ocl.py", line 65, in __init__
    deps = self.plandict_op_group(op_type, op_list, deps)
  File "/home/menelou/MasterArbeit/Code/Nengo/nengo_voja/local/lib/python2.7/site-packages/nengo_ocl/sim_ocl.py", line 78, in plandict_op_group
    plans = getattr(self, 'plan_' + op_type.__name__)(op_list)
  File "/home/menelou/MasterArbeit/Code/Nengo/nengo_voja/local/lib/python2.7/site-packages/nengo_ocl/sim_ocl.py", line 112, in plan_SimPyFunc
    fn_name = fn.__name__
AttributeError: 'Signal' object has no attribute '__name__'
```
`Signal` is one of the used class in `model_2_offline_9`

**Comment by hunse** [comment]
The pip version will not work for what you want to do. Using the dev version, you're getting the first error because you also need the dev version of Nengo.

**Comment by MenelikV** [comment]
I got the following error (with dev version from Nengo and Nengo_ocl) :
```python
Traceback (most recent call last):
  File "model_2_offline_9_ocl.py", line 481, in <module>
    model = main(sys.argv[1], sys.argv[2])
  File "model_2_offline_9_ocl.py", line 475, in main
    change_every = change_every, nb_signals = nb_signals)
  File "model_2_offline_9_ocl.py", line 423, in run_and_plot
    sim = nengo_ocl.Simulator(model, dt, context = ctx)
  File "/home/menelou/MasterArbeit/test_ocl/nengo_ocl-master/nengo_ocl/sim_ocl.py", line 65, in __init__
    self, network=network, dt=dt, seed=seed, model=model)
  File "/home/menelou/MasterArbeit/test_ocl/nengo_ocl-master/nengo_ocl/sim_npy.py", line 442, in __init__
    self._plan.extend(self.plan_op_group(op_type, op_list))
  File "/home/menelou/MasterArbeit/test_ocl/nengo_ocl-master/nengo_ocl/sim_npy.py", line 453, in plan_op_group
    return getattr(self, 'plan_' + op_type.__name__)(ops)
  File "/home/menelou/MasterArbeit/test_ocl/nengo_ocl-master/nengo_ocl/sim_ocl.py", line 227, in plan_SimNeurons
    % neuron_class.__name__)
ValueError: Unsupported neuron type 'AdaptiveLIFRate'
```
So, I think I should change my neuron type to LIFRate, right (since it's currently supported) ?

**Comment by hunse** [comment]
Yes, you have to use `LIFRate` or `LIF`. I haven't implemented `AdaptiveLIFRate` yet, but if this is something you need, feel free to file another issue and I'll get around to it sometime soon hopefully.

**Comment by MenelikV** [comment]
Thanks for the answer ! :)
